name = "morse_code_translator"
version = "2.0.0"

description = "Morse Code Translator"
licences = ["MIT"]
links = [
  {title = "Website", href = "https://salif.github.io/morse-code-translator"},
  {title = "Codeberg", href = "https://codeberg.org/salif/morse-code-translator"},
]
repository = {type = "github", user = "salif", repo = "morse-code-translator"}

target = "javascript"
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
